### ISSUE TITLE
Build failure calls for metadata revision

### ISSUE THREAD

**Issue by chris-martin** [lexi-lambda/monad-validate#3]
https://github.com/freckle/freckle-app/actions/runs/5787709837/job/15685197687?pr=110

> monad-validate-1.2.0.1/src/Control/Monad/Validate/Internal.hs:534:54: error: [GHC-88464]
> Variable not in scope: (<=<)
>
> ```
> 534 | validateToErrorWith f = either (throwError . f) pure <=< runValidateT
>     |                                                      ^^^
> ```

The `Control.Monad.Except` module from `mtl` was previously re-exporting all of `Control.Monad`, so that's where `<=<` had been imported from. As of 2.3, this is no longer the case, so I think a constraint `mtl < 2.3` should be added to the `monad-validate-1.2.0.1` release (and potentially others).

**Comment by lexi-lambda** [comment]
I’ve made the relevant revisions to every other version on Hackage.
